name: Build and Copy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Build Flutter app
        run: flutter build web --release

      - name: Copy build files to build branch
        run: |
          mkdir -p build
          cp -r build/web/* build/
          git checkout -b build
          git add build
          git commit -m "Update build files"
          git push origin build

      - name: Clean up
        run: rm -rf build
